### ISSUE TITLE
Show the name of the headset on the Tooltip

### ISSUE THREAD

**Issue by ArthurGamerHD** [auto94/HyperX-Cloud-2-Battery-Monitor#5]
With the addition of more supported headset models, this app is not more just about the Cloud 2, 
so, a nice addition would be displaying the actual Name of the headset on the tooltip, 
since you don't really know what this number on your taskbar represents without open the tooltip,  
and after opening the tooltip, you don't actually know what exactly is with that amount of battery until opening the full app and reading the name of the headset 

i have an example image:
  
![image](https://github.com/auto94/HyperX-Cloud-2-Battery-Monitor/assets/11463584/83df1ec9-0d5d-4d98-99e0-a7e3b6e97512)

**Comment by auto94** [comment]
I've been thinking it over and I was initially against this, since who doesn't know what headset they have? 
But thinking about it, I guess some people have other wireless peripherals and therefore might have multiple battery icons/widgets so I think this makes sense yeah.

You want to do it (code it I mean)?

**Comment by auto94** [comment]
Sorry for the delay, busy couple of weeks.
Merged to main, I'll make a new release if/when a couple more changes pile up. 
Thanks for the help!

Closing the issue.
